### PR TITLE
Touhoudb: change to .com

### PR DESCRIPTION
**Pull request by BlackPowerade**
Domain was changed to .com at some point

### CODE REVIEW

**Comment by NetNerd** [comment]
Thanks for catching that

**Comment by NetNerd** [comment]
By the way, is the plugin working for TouhouDB?
It's been ages since I even really tested that tbh.

**Comment by BlackPowerade** [comment]
Didn't seem like it worked. when I tried the plugin it queried all of the lyrics databases but came up with nothing. I don't know if any API's changed or anything, but this seems like the most likely cause.

**Comment by NetNerd** [comment]
Ah, so you didn't compile a version to test with the change. I'll have to get the build running on my current system to test then.

**Pull request merged**
